language: groovy
jdk:
- openjdk6
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: XPk4QN3jB4h7+1m/55ijcM4HPYY1IO4UITx/9oZN9osv21hD8V4hvQZ+Cgs0TCqTStGoSu8tgIOkfT9loVgxLboQBVoj/FPm3m7Kiv8no6OwVf+wEnACKJpOobpYitjp49C4baZQCl+6BAmkHxFmvRJptnr+11+eZCdQ3ILoESQ=
  - secure: Kq71InNQ/KMpRIutPmk7lWZPckTn/dOiPIc5p37xEMJDIcTXh48dgvsvTcdnmJWxsUmsfmXKlZBYDbAS+CNVzdY0dbvXZZKDf6dxB5uwWOQ8bWBcbByPbNvEgwlD0CvTw76ebbwgPL/lB5hTgtkZYE4xr4tS/xQhfWY+QjScnJ4=
  - secure: nv8UnZZ+XlUfOk5aB0d2GMyCK/8fkRdumuVUhKVf13wuGqmUSBaDzAhCKfKKNVpvhN8cipVhiUF+1Eme3DIZv4Gl+eA8Ek7XWXMy0O/pC+zf3U4anFlbovjUX4TPHyIclnFq4IVsegJKcLIQA8zIdqUOQrOpJbBGFVuL4m6khgg=
