language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: tsNpXxYjlTQgeVMepYNOU4q1TFfNuIyt5RL2jO2K4PMbKlH1V+izJ1YOQSgDP4rfHnO5TvYvTEGartalG1pIriSRFppg6EUr4INI87k3ZNqO2OlbwmPMg0K89ohqP5pK9OpOnK3k7OwcwUmnPgp81un6br41iuBTbi8cMFWA8K8=
  - secure: C+ALYT6phdsak5KOoNciVdRSKUHFc7ynwl5AfwsIxwr6yuhsMwAwmE4ZmDsYFtP3grWFQ1cjjZ5WZlyW4Vs/3JGtu4CEZzRR+mvLimvPwNvpkVqYzjw7BTravU7bo7r/tpJ+1Er14zdIfyqyWgtJP2AizgRzXN+64shfMNentRA=
  - secure: g+X+TQ4/T+de/sgx1wvmcE7EIjTx+pGTtCmtcQPQCKvQ045Bgk5X8U9He1EqUpsTMbpIAA6PddSHpu+NaOCUP9daPj2rg1haj2HkV804txu37fXagN/FiWrPQr7sW2G/0ogp4M4Bd5AR6UW2pLWNtsRgoDYdlGxe+nbH4GDzX7Y=
  - secure: VZhvZHRI5ndZqCHZDdNkApOIRbrRNrfpaV6WLWkwWQPVZ4fKgGogZsFVBhWqNXZA2AmaIhNsq9LERP8DS1/yWSKwbvgmTIR7ISY9fwLNh4gWQMlG7o1+8wrXraXhsvv/x3YeCUaQ/GxXLfb1k2VqNq5Eg1xf6ee9uKzaBOaBssY=
  - secure: G2XVuFQYwr1vD3gKXLydzUHxrUytKjTw7DlSAtA8YrmTBurN+PeHWlszbmeYzk0+NGYdPoy96SPY0uD8FAROutnF3zSluCt+nuY75ZwaEeZhIIJqHVSpt6iQvtUxXIFnkWhLyxVj2D/Nv1uYMCILWtVRnPhVODjczFU25j4xbso=
