language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: UdGSraXB6ypFDv46lBaxQtKQU99DjXC0Sem6C/0DN2fTF8RmtHUHrn+rxfIQXUdyDFbvZB9AkmVITFF3XcZo9f1ZmMPie2ds9D/THNU/1mje9ObM8TCBE5ggDWAyZ4AXtuzu9w7hhE13S3XuMy/16a2aKV4rdwmtaF+/8GLD4tc=
  - secure: UQbuFF7aDursnjU5LCk2orfhkkbmSfg6X1BL4fXYFWPzvbxKDyzP0Wxvjqi1hyWZ1Nn8amBC0b40CxAW/nVL65f2hJa8VcVr1d+LNDhOGMXX1aNJ4i9UnNtop0z3YFtFWYYtWnUHKSiLZ1djKrw68ME2a/TCaZSqHFQ5HqyUutQ=
