language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Jeff Scott Brown"
  - GIT_EMAIL="jeff@jeffandbetsy.net"
  - secure: HDlUKPlcsbSamOPv6hz5DBadGqRt727D1dQcFMHwRVze1lVyhehbSpEJRcjnttW7ZI4OWT2UX4hl1SNrP6xiOcseSLv3U04nlqC6cIjUCFd7KZKM7oz8v7AMhXG52Jq4+0g+jCQntynK+pUos0fSSdIpeAWzs9Aw5cW8KO51eVk=
  - secure: IIjOgVn8IoVIN2kldrt8Q4tYWfYCyQqlNjmkGLMyM14WHNcLHiLArDd/zZdxkgudWPxhxk0aZRpOekWa/Lw4f2leWjNKewR/MGRATiMfV5apmU9f5M46vZdvVJhIi5Ja5RL9ReuAk40Gtly2edvLflugDcySqDhd3hLdMGcMMpo=
  - secure: Htz8SS2WsmBbiC/7WtjLeUAg1cZUEjus1UdVZIPBzW+Br3UrOsBcnfwK0rHsVhBs+Pr9XJiPxdyweEPCVZ5OaPf3jOsZvAv+QkmwoDtRSju2dSHZtTTRT/iTD7v5WfkStYGMaa32qiEac9UDM16oWVto4AWAwNDgh5nnY+u0GFQ=
  - secure: Qdxnsz9bYT1S0fCP3kjakS37FRtolgke8nj+fxhaH2O8egUYwmo9POYYHGIhqpxdPA2grIuPi7i0/SYtdnTy2ev5p2rBlbeXK6+37vL7Oi0eJCx9T7zcO63NNlbkNjToeFhwrVN6Sjav+W4eH5Gd7QmiXBN2oE8ci5i4gVHj4JE=
  - secure: CzWu4cNNUMgLbHvkapkwvIsvwN3ls/AZBmdQvmgaIIKbHSTBTbsrW3Ww5gsf3Rn5dKotq74MFSZdJqmlIZ4Xh1PMzEq6tD7G/p2kSa/tjJDpVMHRMHWC8VNRmU9C7YvReZKxC0JwuU/GrwndPYUxZtuyyWaJlBrR7omqaws/Bck=
